import { useEffect, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { Link } from 'react-router-dom'
import { AreaChart, BarChart3, Bot, Check, ChevronRight, Clipboard, Download, FileText, Loader2, Mic, Plus, Send, Sparkles, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, Line, LineChart } from 'recharts'
import CircularGauge from '@/components/dashboard/CircularGauge'
import { useCopilotStore } from '@/lib/copilot/copilotStore'
import type { CopilotMessage, CopilotWidget } from '@/lib/copilot/tools'

const suggestions = ['Open critical alerts', "Today's risk score", 'Weekly trend', 'Generate report', 'Riskiest zone']
type SpeechResultEvent = { results: ArrayLike<ArrayLike<{ transcript: string }>> }
type SpeechRecognitionLike = { onresult: (event: SpeechResultEvent) => void; start: () => void }

function Widget({ widget }: { widget: CopilotWidget }) {
  if (widget.type === 'alerts') return <div className="mt-3 space-y-2">{widget.alerts.map(alert => <div key={alert.id} className="rounded-lg border border-slate-200 bg-white p-3"><div className="flex items-center justify-between"><span className={`text-[10px] font-bold uppercase ${alert.severity === 'Critical' ? 'text-red-600' : 'text-orange-600'}`}>{alert.severity} · {alert.zone}</span><span className="text-[10px] text-slate-400">{alert.createdAt}</span></div><p className="mt-1 text-xs text-slate-700">{alert.message}</p><p className="mt-2 text-[10px] text-slate-400">{alert.source}</p></div>)}<Link to="/alerts" className="mt-2 flex items-center justify-center gap-1 rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Open in Alert Management <ChevronRight className="h-3 w-3" /></Link></div>
  if (widget.type === 'risk') return <div className="mt-3 flex items-center gap-4 rounded-lg border border-slate-200 bg-white p-3"><CircularGauge value={widget.score} label="Project risk" size={92} /><div className="min-w-0 flex-1 space-y-2">{widget.zones.map((zone, index) => <div key={zone.name} className="flex items-center justify-between text-xs"><span className="font-medium text-slate-700">{index + 1}. {zone.name}</span><span className="text-slate-500">{zone.score}/100 · {zone.openHazards} open</span></div>)}</div></div>
  if (widget.type === 'zones') return <div className="mt-3 space-y-2">{widget.zones.map(zone => <div key={zone.name} className="flex justify-between rounded-lg bg-white p-2 text-xs"><span>{zone.name}</span><b>{zone.score}/100</b></div>)}</div>
  if (widget.type === 'chart') return <div className="mt-3 rounded-lg border border-slate-200 bg-white p-3"><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-slate-700">{widget.chart === 'bar' ? <BarChart3 className="h-3.5 w-3.5" /> : <AreaChart className="h-3.5 w-3.5" />}{widget.title}</div><div className="h-40"><ResponsiveContainer width="100%" height="100%">{widget.chart === 'bar' ? <BarChart data={widget.data}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey={widget.xKey} fontSize={10} /><YAxis fontSize={10} /><Tooltip /><Bar dataKey={widget.yKeys[0]} fill="#f97316" radius={[3, 3, 0, 0]} /><Bar dataKey={widget.yKeys[1]} fill="#94a3b8" radius={[3, 3, 0, 0]} /></BarChart> : <LineChart data={widget.data}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey={widget.xKey} fontSize={10} /><YAxis fontSize={10} /><Tooltip /><Line type="monotone" dataKey={widget.yKeys[0]} stroke="#f97316" strokeWidth={2} /><Line type="monotone" dataKey={widget.yKeys[1]} stroke="#64748b" strokeWidth={2} /></LineChart>}</ResponsiveContainer></div></div>
  if (widget.type === 'forecast') return <div className="mt-3 rounded-lg border border-orange-200 bg-orange-50 p-3"><p className="text-xs font-bold text-orange-900">{widget.title}</p><p className="mt-1 text-lg font-bold text-orange-700">{widget.value}</p><p className="text-[11px] text-orange-800">{widget.confidence}</p><ul className="mt-2 space-y-1 text-[11px] text-slate-700">{widget.actions.map(action => <li key={action} className="flex gap-1"><Check className="mt-0.5 h-3 w-3 text-orange-600" />{action}</li>)}</ul></div>
  if (widget.type === 'report') return <div className="mt-3 rounded-lg border border-slate-200 bg-white p-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-orange-600" /><div><p className="text-xs font-bold text-slate-800">{widget.title}</p><p className="text-[10px] text-slate-500">{widget.period}</p></div></div><ul className="my-3 space-y-1 text-xs text-slate-600">{widget.highlights.map(item => <li key={item}>• {item}</li>)}</ul><button className="flex w-full items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700"><Download className="h-3.5 w-3.5" /> Download PDF</button></div>
  return <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3"><p className="text-xs font-semibold text-amber-900">Confirm: {widget.label}</p><p className="mt-1 text-[11px] text-amber-800">{widget.detail}</p><ConfirmButton widget={widget} /></div>
}

function ConfirmButton({ widget }: { widget: Extract<CopilotWidget, { type: 'confirm' }> }) {
  const confirm = useCopilotStore(state => state.confirm)
  const [done, setDone] = useState(false)
  return <button disabled={done} onClick={async () => { await confirm(widget.action); setDone(true) }} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg bg-amber-600 px-3 py-2 text-xs font-semibold text-white disabled:bg-slate-300">{done ? 'Action submitted' : 'Confirm action'} <Check className="h-3.5 w-3.5" /></button>
}

function Message({ item }: { item: CopilotMessage }) {
  const [copied, setCopied] = useState(false)
  const copy = async () => { await navigator.clipboard?.writeText(item.text); setCopied(true); window.setTimeout(() => setCopied(false), 1200) }
  if (item.role === 'user') return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="flex justify-end"><div className="max-w-[85%] rounded-2xl rounded-br-sm bg-slate-900 px-3 py-2 text-sm text-white">{item.text}</div></motion.div>
  return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="flex gap-2"><div className="mt-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-orange-100"><Bot className="h-3.5 w-3.5 text-orange-600" /></div><div className="min-w-0 max-w-[90%] text-sm text-slate-700">{item.status === 'pending' ? <div className="flex items-center gap-2 text-slate-500"><Loader2 className="h-4 w-4 animate-spin" />Thinking…</div> : <><p className="whitespace-pre-wrap">{item.text}</p>{item.source && <p className="mt-2 text-[10px] font-medium text-slate-400">Based on {item.source} data, as of {item.asOf}.</p>}{item.widget && <Widget widget={item.widget} />}<button onClick={copy} className="mt-2 flex items-center gap-1 text-[10px] text-slate-400 hover:text-slate-700"><Clipboard className="h-3 w-3" />{copied ? 'Copied' : 'Copy'}</button></>}</div></motion.div>
}

export default function CopilotChat() {
  const { open, close, messages, busy, activeTool, toggle, newConversation, send } = useCopilotStore()
  const [input, setInput] = useState('')
  const listRef = useRef<HTMLDivElement>(null)
  useEffect(() => { listRef.current?.scrollTo({ top: listRef.current.scrollHeight, behavior: 'smooth' }) }, [messages, open])
  const submit = async (value = input) => { if (!value.trim()) return; setInput(''); await send(value) }
  const voice = () => { const Recognition = (window as Window & { SpeechRecognition?: new () => SpeechRecognitionLike; webkitSpeechRecognition?: new () => SpeechRecognitionLike }).SpeechRecognition || (window as Window & { webkitSpeechRecognition?: new () => SpeechRecognitionLike }).webkitSpeechRecognition; if (!Recognition) return; const recognition = new Recognition(); recognition.onresult = event => setInput(event.results[0][0].transcript); recognition.start() }
  return <><button onClick={toggle} aria-label="Open BuildSure copilot" className="fixed bottom-6 right-6 z-40 flex items-center gap-2 rounded-full bg-orange-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-orange-600/25 transition hover:bg-orange-700"><Sparkles className="h-4 w-4" /> Copilot</button>{open && <div className="fixed inset-0 z-50 bg-slate-900/20" onClick={close}><section onClick={event => event.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-md flex-col bg-slate-50 shadow-2xl"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-orange-100"><Sparkles className="h-5 w-5 text-orange-600" /></div><div><h2 className="font-bold text-slate-800">BuildSure Copilot</h2><p className="text-[11px] text-slate-500">Grounded in platform data</p></div></div><div className="flex items-center gap-1"><button onClick={newConversation} aria-label="New conversation" title="New conversation" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Plus className="h-4 w-4" /></button><button onClick={close} aria-label="Close copilot" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X className="h-4 w-4" /></button></div></header><div ref={listRef} className="flex-1 space-y-5 overflow-y-auto p-4">{messages.map(item => <Message key={item.id} item={item} />)}</div>{busy && activeTool && <div className="border-t border-slate-200 bg-white px-4 py-2 text-[11px] text-slate-500"><Loader2 className="mr-1 inline h-3 w-3 animate-spin" />{activeTool}</div>}<div className="border-t border-slate-200 bg-white p-4"><div className="mb-3 flex gap-2 overflow-x-auto pb-1">{suggestions.map(suggestion => <button key={suggestion} onClick={() => submit(suggestion)} className="whitespace-nowrap rounded-full border border-slate-200 px-3 py-1.5 text-[11px] text-slate-600 hover:border-orange-300 hover:text-orange-700">{suggestion}</button>)}</div><div className="flex items-end gap-2 rounded-xl border border-slate-200 bg-slate-50 p-2 focus-within:border-orange-400"><textarea value={input} onChange={event => setInput(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void submit() } }} placeholder="Ask about your project…" rows={1} className="max-h-24 min-h-[32px] flex-1 resize-none bg-transparent px-1 py-1 text-sm outline-none" /><button onClick={voice} aria-label="Use voice input" title="Use voice input" className="rounded-lg p-2 text-slate-500 hover:bg-white hover:text-orange-600"><Mic className="h-4 w-4" /></button><button onClick={() => void submit()} disabled={!input.trim() || busy} aria-label="Send message" className="rounded-lg bg-orange-600 p-2 text-white disabled:bg-slate-300"><Send className="h-4 w-4" /></button></div></div></section></div>}</>
}