import { useEffect, useState } from 'react'
import { Download, FileText, Plus, RefreshCw, X } from 'lucide-react'
import { api } from '@/lib/api'

const projectId = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'
const reportTypes = ['executive_summary', 'daily_site', 'safety_analysis', 'compliance_audit', 'insurance_assessment']

function downloadReport(report: any) {
  const text = `${report.type.replace(/_/g, ' ').toUpperCase()}\nGenerated: ${new Date(report.generated).toLocaleString()}\nGenerated by: ${report.generated_by}\n\n${report.summary || 'No summary available.'}`
  const url = URL.createObjectURL(new Blob([text], { type: 'text/plain' }))
  const link = document.createElement('a')
  link.href = url
  link.download = `${report.type}-${report.id}.txt`
  link.click()
  URL.revokeObjectURL(url)
}

export default function Reports() {
  const [reports, setReports] = useState<any[]>([])
  const [type, setType] = useState(reportTypes[0])
  const [format, setFormat] = useState('txt')
  const [selected, setSelected] = useState<any>()
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')

  const load = () => {
    setLoading(true)
    api.get(`/projects/${projectId}/reports`).then(response => setReports(response.data.data || [])).catch(() => setError('Reports could not be loaded.')).finally(() => setLoading(false))
  }
  useEffect(load, [])

  const generate = async () => {
    setGenerating(true)
    setError('')
    try { const response = await api.post(`/projects/${projectId}/reports`, { report_type: type, file_format: format }); setReports(current => [response.data.data, ...current]) }
    catch { setError('Report generation failed.') }
    finally { setGenerating(false) }
  }

  return <div>
    <div className="flex items-center justify-between gap-4 mb-6"><div><h2 className="text-2xl font-bold text-slate-800">Reports</h2><p className="mt-1 text-sm text-slate-500">Generate auditable project intelligence from current site data.</p></div><button onClick={load} className="rounded-lg border border-slate-200 p-2 text-slate-600" aria-label="Refresh reports"><RefreshCw className="h-4 w-4" /></button></div>
    <div className="card mb-5"><div className="flex items-center gap-2 mb-3"><Plus className="h-5 w-5 text-accent-orange" /><h3 className="font-bold text-slate-800">Generate report</h3></div><div className="flex flex-wrap items-end gap-3"><label className="text-sm text-slate-600">Report type<select value={type} onChange={event => setType(event.target.value)} className="mt-1 block rounded-lg border border-slate-200 px-3 py-2 text-sm">{reportTypes.map(item => <option key={item} value={item}>{item.replace(/_/g, ' ')}</option>)}</select></label><label className="text-sm text-slate-600">Format<select value={format} onChange={event => setFormat(event.target.value)} className="mt-1 block rounded-lg border border-slate-200 px-3 py-2 text-sm"><option value="txt">Text summary</option><option value="pdf">PDF-ready summary</option></select></label><button onClick={() => void generate()} disabled={generating} className="rounded-lg bg-accent-orange px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{generating ? 'Generating...' : 'Generate'}</button></div></div>
    {error && <div className="mb-4 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
    {loading ? <p className="py-8 text-center text-slate-500">Loading reports...</p> : <div className="grid gap-4">{reports.map(report => <div key={report.id} className="card flex items-center justify-between gap-4"><div className="flex items-center gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-100"><FileText className="h-5 w-5 text-blue-600" /></div><div><p className="font-bold text-slate-800">{report.type.replace(/_/g, ' ')}</p><p className="text-sm text-slate-500">{report.format.toUpperCase()} · {new Date(report.generated).toLocaleString()}</p><p className="mt-1 text-sm text-slate-600 line-clamp-1">{report.summary || 'No summary available.'}</p></div></div><div className="flex gap-2"><button onClick={() => setSelected(report)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-medium text-slate-700">Preview</button><button onClick={() => downloadReport(report)} className="rounded-lg bg-slate-900 p-2 text-white" aria-label="Download report"><Download className="h-4 w-4" /></button></div></div>)}{reports.length === 0 && <p className="py-8 text-center text-slate-500">No reports generated yet.</p>}</div>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" onClick={() => setSelected(undefined)}><div className="w-full max-w-xl rounded-xl bg-white p-6" onClick={event => event.stopPropagation()}><div className="flex items-center justify-between"><h3 className="font-bold text-slate-800">Report preview</h3><button onClick={() => setSelected(undefined)} aria-label="Close preview"><X className="h-5 w-5" /></button></div><p className="mt-4 whitespace-pre-wrap text-sm text-slate-600">{selected.summary || 'No summary available.'}</p></div></div>}
  </div>
}
