import { useState } from 'react'
import { Bell, Check, Play, RotateCcw, Save, ShieldCheck, Siren } from 'lucide-react'
import { useEmergencyStore } from '@/lib/emergency/emergencyStore'
import type { IncidentType, UserRole } from '@/lib/emergency/types'

const defaults = { role: 'SITE_MANAGER', zone: 'Zone B', incidentType: 'Injury', emailAlerts: true, browserAlerts: true, dailyReports: true, reportFormat: 'txt' }
type Preferences = typeof defaults

function readPreferences(): Preferences { try { return { ...defaults, ...JSON.parse(localStorage.getItem('buildsure_preferences') || '{}') } } catch { return defaults } }

export default function Settings() {
  const activate = useEmergencyStore(state => state.activate)
  const [preferences, setPreferences] = useState<Preferences>(readPreferences)
  const [saved, setSaved] = useState(false)
  const [started, setStarted] = useState(false)
  const update = <K extends keyof Preferences>(key: K, value: Preferences[K]) => setPreferences(current => ({ ...current, [key]: value }))
  const save = () => { localStorage.setItem('buildsure_preferences', JSON.stringify(preferences)); localStorage.setItem('buildsure_role', preferences.role); setSaved(true); window.setTimeout(() => setSaved(false), 2000) }
  const reset = () => { setPreferences(defaults); localStorage.removeItem('buildsure_preferences'); localStorage.setItem('buildsure_role', defaults.role) }
  const demo = async () => { const role = preferences.role as UserRole; const ok = await activate(preferences.incidentType as IncidentType, preferences.zone, 'Settings Controller', role === 'SAFETY_OFFICER' || role === 'SITE_MANAGER' ? role : 'SITE_MANAGER'); setStarted(ok) }

  return <div><div className="flex items-center justify-between"><div><h2 className="text-2xl font-bold text-slate-800">Settings</h2><p className="mt-1 text-sm text-slate-500">Configure workspace behavior, notifications, and emergency response defaults.</p></div><div className="flex gap-2"><button onClick={reset} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600"><RotateCcw className="h-4 w-4" /> Reset</button><button onClick={save} className="flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><Save className="h-4 w-4" /> Save</button></div></div>{saved && <div className="mt-4 flex items-center gap-2 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700"><Check className="h-4 w-4" /> Preferences saved.</div>}
  <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="card"><h3 className="font-bold text-slate-800">Workspace</h3><div className="mt-4 space-y-4"><label className="block text-sm text-slate-600">Current role<select value={preferences.role} onChange={event => update('role', event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 px-3 py-2"><option value="SITE_MANAGER">Site manager</option><option value="SAFETY_OFFICER">Safety officer</option><option value="EXECUTIVE">Executive</option><option value="WORKER">Worker</option></select></label><label className="block text-sm text-slate-600">Default project zone<input value={preferences.zone} onChange={event => update('zone', event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 px-3 py-2" /></label></div></section><section className="card"><h3 className="flex items-center gap-2 font-bold text-slate-800"><Bell className="h-5 w-5 text-accent-orange" /> Notifications</h3><div className="mt-4 space-y-3">{([['emailAlerts', 'Email alert notifications'], ['browserAlerts', 'Browser alert notifications'], ['dailyReports', 'Daily report reminders']] as const).map(([key, label]) => <label key={key} className="flex items-center justify-between text-sm text-slate-600">{label}<input type="checkbox" checked={preferences[key]} onChange={event => update(key, event.target.checked)} /></label>)}</div></section><section className="card lg:col-span-2"><h3 className="flex items-center gap-2 font-bold text-slate-800"><Siren className="h-5 w-5 text-red-600" /> Emergency response defaults</h3><div className="mt-4 grid gap-4 md:grid-cols-3"><label className="text-sm text-slate-600">Incident type<select value={preferences.incidentType} onChange={event => update('incidentType', event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 px-3 py-2"><option>Injury</option><option>Structural</option><option>Fire</option><option>Gas Leak</option><option>Other</option></select></label><label className="text-sm text-slate-600">Report format<select value={preferences.reportFormat} onChange={event => update('reportFormat', event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 px-3 py-2"><option value="txt">Text summary</option><option value="pdf">PDF-ready summary</option></select></label><button onClick={() => void demo()} disabled={started} className="mt-6 flex items-center justify-center gap-2 rounded-lg bg-red-600 px-4 py-2.5 text-sm font-bold text-white disabled:bg-slate-400"><Play className="h-4 w-4" /> {started ? 'Demo active' : 'Simulate emergency'}</button></div></section></div><div className="mt-4 flex items-center gap-2 text-sm text-slate-600"><ShieldCheck className="h-4 w-4 text-green-600" /> Emergency actions are restricted by role.</div></div>
}
